<br>

# Working with json(JavaScript Object Notation) or sql(Structured Query Language):

<br>

<br>

### Json

`json is universal because all most all the programming language understand it. If in a server we have an api, the api response data to us in json format.`

<br>

### SQL

`When we use dataset from  a database. `

<br>
<br>

In [2]:
import pandas as pd

<br>

---

<br>
<br>

# Working With JSON

<br>
<br>

---

<br>

<br>

### Load file from local computer

<br>

In [7]:

# We have so many similar parameter that we see in  **pd.read_csv()** see the documentation

df = pd.read_json("dataset/train.json")
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

<br>

### Load file from internet:

<br>

In [6]:
df = pd.read_json("https://api.exchangerate-api.com/v4/latest/INR")
df.head(5)

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-06-23,1719100801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-06-23,1719100801,0.0439
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-06-23,1719100801,0.8480
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-06-23,1719100801,1.1200
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-06-23,1719100801,4.6400

<br>

---

<br>
<br>

# Working With SQL

<br>
<br>

---

<br>